- translations/lxqt-about_ja.desktop
Hello.
I wrote Japanese desktop file.
> Add Japanese desktop file

- translations/lxqt-about_de.desktop
And here is the german translation of the .desktop file...
> Added german translation of .desktop file.

- translations/lxqt-about_el.desktop
- translations/lxqt-about_el.ts
- translatorsinfo/translators_el.info
Remove country variant from language code
Update translator info in translators_el.info
> Add Greek (el) translation

- resources/lxqt-about.desktop.in
Fixed categories to System and Documentation
Fixed Show-only in LXQt
> Desktop file fixed

- .gitignore
Looks like a copy paste mistake.
> .gitignore: Fix typo

- translations/lxqt-about_pl.desktop
Signed-off-by: Marcin Mikołajczak <me@m4sk.in>
> updated Polish translation

- CMakeLists.txt
> Set patch version 0

- CMakeLists.txt
- aboutdialog/technicalinfo.cpp
- translatorsinfo/translatorsinfo.cpp
- translatorsinfo/translatorsinfo.h
Replaced by the ranged-based for loop.
Qt 5.7.1 is required. We use qAsConst().
> Drop Qt foreach

- CMakeLists.txt
- translations/CMakeLists.txt
> Set cmake_minimum_required(VERSION 3.1.0 FATAL_ERROR)

- translatorsinfo/translatorsinfo.cpp
- translatorsinfo/translatorsinfo.h
Changes are discussed on issue #97
> translatorsinfo: sort translators by language

- CHANGELOG
- CMakeLists.txt
* Bumped version to 0.14.1
* Only translations was changed.
> Point release lxqt-about 0.14.1

- CMakeLists.txt
They are already set with LXQtCompilerSettings.
> Remove implicit casts definitions

- aboutdialog/lxqtaboutdialog.cpp
http://razor-qt.org -> https://blog.lxqt.org/2014/11/in-memory-of-razor-qt/
Fixes #122
> Fixed Razor-qt link

- translatorsinfo/translators_cs.info
See history on weblate.lxqt.org (when it will be up again).
> Added Pavel Borecki into translators credits

- translations/lxqt-about_tr.ts
- translatorsinfo/translators_tr.info
Updated Turkish translations for more regular Turkish.
> Update Turkish translations

- translatorsinfo/translators_cs.info
> Fixed translators_cs.info

- translatorsinfo/translators_nb_NO.info
https://translate.lxqt-project.org/user/kingu/
> Norwegian Bokmål translator added

- translatorsinfo/translators_tr.info
I have been spend time to localization for Turkish. Therefore I added my name.
> Added my info as a translator

- translatorsinfo/translators_ro.info
When I added myself I forgot to remove the ”#” so the changes were invalid.
> Fixing #195

- aboutdialog/lxqtaboutdialog.cpp
Not sure about the "development".
> Added wiki, updated links

- translatorsinfo/translatorsinfo.cpp
- translatorsinfo/translatorsinfo.h
> translatorsinfo: Sort shown language name alphabetically

- CMakeLists.txt
- aboutdialog/technicalinfo.cpp
- main.cpp
- translatorsinfo/translatorsinfo.cpp
Compiled without `lxqt2-` prefix.
> Port to Qt6
